### ISSUE TITLE
[docs] New icon

### ISSUE THREAD

**Issue by Mutated1994** [cch123/supermonkey#10]
I made an icon for `supermonkey`. I hope you like it.

![gopher](https://user-images.githubusercontent.com/29589055/102566226-0a23b700-411a-11eb-879e-8b58b6a1c8d6.png)

**Comment by Mutated1994** [comment]
@cch123 Dude, how about this color? 😃

**Comment by cch123** [comment]
牛逼。。兼职美工

**Comment by cch123** [comment]
来个 PR 换一发

**Comment by Mutated1994** [comment]
> 来个 PR 换一发

OK. I'll do it right away.
